### PR TITLE
Make generic

### PR DESCRIPTION
**Pull request by avinoth**
* Added the necessary initializer and moved the sensitive values to ENV VARs, to make it more generic.
* Removed the APP ID that was in a view.

### CODE REVIEW

**Comment by codelitt** [comment]
Great addition. Thanks for the PR. :thumbsup:

One request before I merge: Would you mind adding in the README.md documentation how to add environment variables for beginner devs? I can foresee that becoming a question that gets asked a lot.

**Comment by avinoth** [comment]
You mean adding locally?

**Comment by codelitt** [comment]
Yes. I guess there are two options (unless I'm forgetting one). 

1. Add to secrets.yml/create a `local.yml` file to handle it and load it up. (Main issues here are people need to ensure they've got that file in their .gitignore otherwise disaster)

2. Set the environment variables in Unix ( `export $(cat .env)` or  `export FROM_EMAIL='myname@gmail.com'` ) 

Thoughts? I just think because of the nature of this app, that there may be questions around how to set it. 

Maybe the best way to handle it is to just link them to a good resource like this: http://railsapps.github.io/rails-environment-variables.html

**Comment by avinoth** [comment]
@codelitt Exactly my thought, there are always mistakes happening and we don't want to solving issues in setting up the env vars, I'll add a link the resource you mentioned, it seems good...  Thoughts?

**Comment by codelitt** [comment]
@avinoth Sounds great.

**Comment by avinoth** [comment]
@codelitt Done!

**Comment by codelitt** [comment]
:+1:

**Pull request merged**
