### PR TITLE
Update to Rails 4 #4

### PR DESCRIPTION
**Pull request by kaiomagalhaes**
Hello , I recently did a fork and continued your work on branch rails4.I finished the upgrade and added other test cases , I hope it will be useful , any suggestion just name it.

### CODE REVIEW

**Comment by codelitt** [comment]
Looks fantastic! This is very helpful. I'll update the readme later today and add a contributors section. This is a great open source alternative to LaunchRock. We have developed some MVP landing pages using this that included a survey after people signed up enabling you to ask your early adopters a few questions to gather more information on market fit. I'll see if @Lockyy would like to add them to this. It may be useful to others.

**Comment by codelitt** [comment]
@kaiomagalhaes I've updated the readme and added you to the contributors list.

**Comment by kaiomagalhaes** [comment]
@codelitt thanks! As soon as possible I will make more tests, probably issue #5 =P

**Comment by codelitt** [comment]
@kaiomagalhaes ya it would be great to have better test coverage. It's not awful though! Just posted it here for others to enjoy! https://news.ycombinator.com/item?id=9778022

**Pull request merged**
