### PR TITLE
Add Specs

### PR DESCRIPTION
**Pull request by avinoth**
* Removed Backstagr reference
* Added Spec for application helper method

### CODE REVIEW

**Comment by kaiomagalhaes** [comment]
@avinoth Towards the 100% test coverage!

**Comment by codelitt** [comment]
:+1: Looks good to me!

**Comment by codelitt** [comment]
@kaiomagalhaes looks like the badge didn't update. Is there something we need to do for the test coverage badge to automatically update?

**Comment by avinoth** [comment]
Not sure, why it's not updating.. I've triggered a manual refresh now

**Comment by kaiomagalhaes** [comment]
@codelitt Do you defined the Codeclimate env key on SemaphoriCI?

**Pull request merged**
