### PR TITLE
adding simple button for surveys

### PR DESCRIPTION
**Pull request by kaiomagalhaes**
@codelitt as we talked on #13 I'm adding this button, I also created a example form on google forms. Do you agree with this simple implementation?

@avinoth what you think about it?

### CODE REVIEW

**Comment by avinoth** [comment]
@kaiomagalhaes Why google forms? we can add a column to users table for the feedback, and show them a rails form instead?

**Comment by kaiomagalhaes** [comment]
@avinoth I was thinking on a simple way to the user create and manage the form and the answers. I don't know if implement our own form is a good idea because the user will have to know how to change it.
My focus with this implementation is just say to the user "Did you see? you can just change this url and you will have a form working!"

**Comment by avinoth** [comment]
@kaiomagalhaes I get it.

@codelitt what do you think?

**Comment by codelitt** [comment]
@avinoth @kaiomagalhaes Ya. If someone wants to make a form that is super easy to implement and change to ask questions, then knock it out. But MVP launch pages are meant to be minimal to test an idea. The main goal of this repo is to eliminate the amount of time someone has to spend on it. I'm going to merge this for now. If someone wants to build an easily changed survey form post sign up then feel free, but for now this will help users.

The ability to add some themes/base design would be a good addition because it also minimizes the time someone has to spend on this. Think that is our biggest goal to accomplish.

**Pull request merged**
