### PR TITLE
Reformat Code and add features

### PR DESCRIPTION
**Pull request by avinoth**
* The JS files are placed at application.html.erb moved it to Users.coffee.
* When User Type 2 is clicked ,the User1 form should hide if visible.
* Removed `static#home` it wasn't used anywhere really.
* Added auth token to be passed as param for urls `get_csv` and `index`.
* Added index page to show list of registered users.

### CODE REVIEW

**Comment by avinoth** [comment]
@codelitt go ahead?

**Comment by codelitt** [comment]
@avinoth always make sure someone has had a chance to review your code before merging a pull request please. Either @kaiomagalhaes or myself. It's just good practice before merging to master.

**Comment by kaiomagalhaes** [comment]
if @codelitt dont review first I will do it and make tests tonight

**Comment by avinoth** [comment]
@codelitt Of course.. wow, miscomm, I was asking can you go ahead? not me. :sheep:

**Comment by kaiomagalhaes** [comment]
@avinoth I had understood what you meant, just didn't have time yet =D

**Comment by avinoth** [comment]
@kaiomagalhaes Yeah, sure. Test it whenever you are free I just placed the PR, it's not going to be relevant for anything new to be picked up.

**Comment by codelitt** [comment]
@avinoth No worries. :) I understand now. My bad. Glad we're all on the same page. It's just good practice that we all review each other's work or any contributions coming in from other places. 

Regarding the PR - Can you see #3 in [Contributing](https://github.com/codelitt/launchpage-rails#contributing)? We should add a test for the auth in the users controller to make sure our code is fully tested. After that, then it will be good from my side unless Kaio has any other issues when he looks tonight. 

@kaiomagalhaes Great. Sounds good.

**Comment by avinoth** [comment]
@codelitt I'll add the specs and will update the PR

**Comment by codelitt** [comment]
@avinoth :+1:

**Comment by kaiomagalhaes** [comment]
@avinoth It's great! I did the tests manually and everything works fine, I will only ask for the same thing that @codelitt asked, make some automated tests for: user index and user csv both controller and views.
As you can see today we have a 90% code coverage and would be awesome if we could maintain and increase this number.

**Comment by avinoth** [comment]
@codelitt @kaiomagalhaes Added the specs :+1: 

Check and let me know..

**Comment by kaiomagalhaes** [comment]
Thanks for the update! Looks great for me @avinoth! :smiley_cat:
@codelitt this merge looks fine for me, unless you find any issue please merge :smiley:

**Comment by codelitt** [comment]
Looks great! Thanks! :+1:

**Pull request merged**
